### ISSUE TITLE
Renaming project

### ISSUE THREAD

**Issue by martinheidegger** [pnext/pnext-io#1]
I am working on point-query as an abstraction layer for the data access of pnext. I thought the name was self-explanatory but had to learn that it isn't. How about changing it to `pnext-api`?

**Comment by dkastl** [comment]
Not sure, if `api` could be be misleading for some. Is it just a "data loader" or is it more?
What about:
-  `pnext-loader`
-  `pnext-io`

**Comment by martinheidegger** [comment]
I will go with `pnext-io` as it makes more sense. (Thanks for the input)
